version: '3.8'

services:
  training:
    image: nvcr.io/nvidia/pytorch:23.07-py3
    container_name: asl-training
    working_dir: /workspace/kaggle-asl-fingerspelling-1st-place-solution
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    env_file:
      - .env
    volumes:
      - .:/workspace/kaggle-asl-fingerspelling-1st-place-solution
    shm_size: 8g
    command: tail -f /dev/null
